// Mock data for videos
export const mockVideos = [
  {
    id: 'video1',
    title: 'How to Build a YouTube Clone with React',
    description: 'In this tutorial, we will build a YouTube clone using React, Tailwind CSS, and more. Learn how to create components, implement routing, and style your application.',
    thumbnail: 'https://picsum.photos/id/1/640/360',
    channelTitle: 'React Mastery',
    channelAvatar: 'https://ui-avatars.com/api/?name=React+Mastery&background=random',
    publishedAt: '2023-07-15T14:30:00Z',
    viewCount: 1250000,
    likeCount: 25000,
    duration: '10:30',
  },
  {
    id: 'video2',
    title: 'Advanced JavaScript Concepts You Need to Know',
    description: 'Dive deep into advanced JavaScript concepts like closures, prototypes, and async/await. Perfect for intermediate developers looking to level up.',
    thumbnail: 'https://picsum.photos/id/2/640/360',
    channelTitle: 'JavaScript Guru',
    channelAvatar: 'https://ui-avatars.com/api/?name=JavaScript+Guru&background=random',
    publishedAt: '2023-08-20T10:15:00Z',
    viewCount: 850000,
    likeCount: 15000,
    duration: '15:45',
  },
  {
    id: 'video3',
    title: 'Tailwind CSS Crash Course',
    description: 'Learn Tailwind CSS from scratch in this comprehensive crash course. We will cover installation, configuration, and building responsive designs.',
    thumbnail: 'https://picsum.photos/id/3/640/360',
    channelTitle: 'CSS Wizards',
    channelAvatar: 'https://ui-avatars.com/api/?name=CSS+Wizards&background=random',
    publishedAt: '2023-09-05T08:45:00Z',
    viewCount: 500000,
    likeCount: 12000,
    duration: '12:20',
  },
  {
    id: 'video4',
    title: 'Building a REST API with Node.js and Express',
    description: 'In this tutorial, we will build a complete REST API using Node.js and Express. Learn how to create routes, handle middleware, and connect to a database.',
    thumbnail: 'https://picsum.photos/id/4/640/360',
    channelTitle: 'Backend Dev',
    channelAvatar: 'https://ui-avatars.com/api/?name=Backend+Dev&background=random',
    publishedAt: '2023-06-10T16:20:00Z',
    viewCount: 750000,
    likeCount: 18000,
    duration: '20:15',
  },
  {
    id: 'video5',
    title: 'React Hooks Explained',
    description: 'A deep dive into React Hooks. Learn how to use useState, useEffect, useContext, and create your own custom hooks.',
    thumbnail: 'https://picsum.photos/id/5/640/360',
    channelTitle: 'React Mastery',
    channelAvatar: 'https://ui-avatars.com/api/?name=React+Mastery&background=random',
    publishedAt: '2023-05-25T11:30:00Z',
    viewCount: 1100000,
    likeCount: 22000,
    duration: '18:30',
  },
  {
    id: 'video6',
    title: 'Modern CSS Techniques',
    description: 'Explore modern CSS techniques like Grid, Flexbox, and CSS Variables. Learn how to create responsive layouts without frameworks.',
    thumbnail: 'https://picsum.photos/id/6/640/360',
    channelTitle: 'CSS Wizards',
    channelAvatar: 'https://ui-avatars.com/api/?name=CSS+Wizards&background=random',
    publishedAt: '2023-04-15T09:45:00Z',
    viewCount: 650000,
    likeCount: 14000,
    duration: '14:10',
  },
  {
    id: 'video7',
    title: 'TypeScript for Beginners',
    description: 'Get started with TypeScript in this beginner-friendly tutorial. Learn about types, interfaces, and how to set up a TypeScript project.',
    thumbnail: 'https://picsum.photos/id/7/640/360',
    channelTitle: 'TypeScript Pro',
    channelAvatar: 'https://ui-avatars.com/api/?name=TypeScript+Pro&background=random',
    publishedAt: '2023-03-20T13:15:00Z',
    viewCount: 450000,
    likeCount: 9000,
    duration: '16:40',
  },
  {
    id: 'video8',
    title: 'Full Stack Development Roadmap 2023',
    description: 'A complete roadmap for becoming a full stack developer in 2023. Learn what technologies to focus on and how to build your portfolio.',
    thumbnail: 'https://picsum.photos/id/8/640/360',
    channelTitle: 'Dev Insights',
    channelAvatar: 'https://ui-avatars.com/api/?name=Dev+Insights&background=random',
    publishedAt: '2023-01-10T15:30:00Z',
    viewCount: 1500000,
    likeCount: 30000,
    duration: '25:15',
  },
  {
    id: 'video9',
    title: 'Docker for Web Developers',
    description: 'Learn how to use Docker for web development. We will cover containers, Docker Compose, and how to set up a development environment.',
    thumbnail: 'https://picsum.photos/id/9/640/360',
    channelTitle: 'DevOps Master',
    channelAvatar: 'https://ui-avatars.com/api/?name=DevOps+Master&background=random',
    publishedAt: '2023-02-05T12:45:00Z',
    viewCount: 350000,
    likeCount: 8000,
    duration: '22:30',
  },
  {
    id: 'video10',
    title: 'Next.js 13 Tutorial',
    description: 'Explore the new features in Next.js 13. Learn about the app directory, server components, and how to build a modern web application.',
    thumbnail: 'https://picsum.photos/id/10/640/360',
    channelTitle: 'Frontend Focus',
    channelAvatar: 'https://ui-avatars.com/api/?name=Frontend+Focus&background=random',
    publishedAt: '2023-10-01T10:00:00Z',
    viewCount: 200000,
    likeCount: 5000,
    duration: '19:45',
  },
  {
    id: 'video11',
    title: 'GraphQL vs REST API',
    description: 'Compare GraphQL and REST APIs. Learn the pros and cons of each approach and when to use one over the other.',
    thumbnail: 'https://picsum.photos/id/11/640/360',
    channelTitle: 'API Architect',
    channelAvatar: 'https://ui-avatars.com/api/?name=API+Architect&background=random',
    publishedAt: '2023-09-15T14:20:00Z',
    viewCount: 300000,
    likeCount: 7000,
    duration: '17:15',
  },
  {
    id: 'video12',
    title: 'Building a Portfolio Website',
    description: 'Learn how to build a professional portfolio website from scratch. We will cover design, development, and deployment.',
    thumbnail: 'https://picsum.photos/id/12/640/360',
    channelTitle: 'Web Craft',
    channelAvatar: 'https://ui-avatars.com/api/?name=Web+Craft&background=random',
    publishedAt: '2023-08-10T11:10:00Z',
    viewCount: 400000,
    likeCount: 10000,
    duration: '15:00',
  },
];

// Mock data for comments
export const mockComments = [
  {
    id: 'comment1',
    text: 'This video was incredibly helpful! I learned so much about React and how to structure my components.',
    author: 'Jane Smith',
    authorAvatar: 'https://ui-avatars.com/api/?name=Jane+Smith&background=random',
    publishedAt: '2023-10-05T14:30:00Z',
    likeCount: 120,
  },
  {
    id: 'comment2',
    text: 'Great tutorial! Could you make a follow-up video on how to implement authentication?',
    author: 'John Doe',
    authorAvatar: 'https://ui-avatars.com/api/?name=John+Doe&background=random',
    publishedAt: '2023-10-04T10:15:00Z',
    likeCount: 85,
  },
  {
    id: 'comment3',
    text: "I've been struggling with this concept for weeks, and your explanation finally made it click for me. Thank you!",
    author: 'Alex Johnson',
    authorAvatar: 'https://ui-avatars.com/api/?name=Alex+Johnson&background=random',
    publishedAt: '2023-10-03T16:45:00Z',
    likeCount: 67,
  },
  {
    id: 'comment4',
    text: 'The code examples were really clear and well-explained. I appreciate the time you put into making this!',
    author: 'Sarah Williams',
    authorAvatar: 'https://ui-avatars.com/api/?name=Sarah+Williams&background=random',
    publishedAt: '2023-10-02T09:30:00Z',
    likeCount: 42,
  },
  {
    id: 'comment5',
    text: 'I found a small bug in the example at 12:45. You should check the console for errors.',
    author: 'Michael Brown',
    authorAvatar: 'https://ui-avatars.com/api/?name=Michael+Brown&background=random',
    publishedAt: '2023-10-01T13:20:00Z',
    likeCount: 28,
  },
];